# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master
- release/*

pr:
- master
- release/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/OpenKh.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: self
  submodules: true | recursive

- script: git submodule update --init --recursive --depth 1
  displayName: 'Download dependencies'

- task: NuGetToolInstaller@0
  displayName: 'Install build tools'

- task: NuGetCommand@2
  displayName: 'Restore packages'
  inputs:
    restoreSolution: '$(solution)'

- powershell: .\pre-build.ps1
  displayName: 'Build tools and libraries metadata'

- task: VSBuild@1
  displayName: 'Build project'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    vsVersion: 'latest'
    msbuildArgs: '/t:Build'
    maximumCpuCount: true

- script: dotnet test --configuration $(buildConfiguration) --logger trx --verbosity normal --collect "Code coverage"
  displayName: 'Run tests'

- task: PublishTestResults@2
  displayName: 'Publish test results'
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish test coverage'
  inputs:
    summaryFileLocation: '**/*.coverage'

- script: dotnet publish --configuration $(buildConfiguration) --verbosity normal --framework netcoreapp3.1 --output $(Build.ArtifactStagingDirectory)/openkh /p:DebugType=None /p:DebugSymbols=false
  displayName: 'Publish project as artifact'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: openkh
    publishLocation: 'Container'
    parallel: true
    parallelCount: 8