theme: jekyll-theme-hacker
title: OpenKh
description: This is a project centralizes all the technical knowledge of Kingdom Hearts series in one place, providing documentation, tools, code libraries and the foundation for modding the commercial games.
google_analytics: UA-56422469-2